const products = [
  {
    id: 1,
    subject: 'Mathmateics',
    location: 'Block 1, Class 108',
    price: 425,
    space: 6,
    desc: 'A field of study that involves the use of numbers, symbols, and mathematical operations to solve problems and analyze data.',
    image: 'assets/webp/Math.webp',
    cartquantity: 0,
  },
  {
    id: 2,
    subject: 'English',
    location: 'Block 5, Class 802',
    price: 350,
    space: 4,
    desc: 'The study of language, literature, and communication in the English language, including grammar, writing, and reading comprehension.',
    image: 'assets/webp/English.webp',
    cartquantity: 0,
  },
  {
    id: 3,
    subject: 'Football',
    location: 'Block 6, Field 1',
    price: 425,
    space: 8,
    desc: "A team sport that involves two teams of 11 players each, with the goal of scoring more goals than the other team by kicking a ball into the opposing team's net.",
    image: 'assets/webp/Football.webp',
    cartquantity: 0,
  },
  {
    id: 4,
    subject: 'History',
    location: 'Block 3, Class 605',
    price: 250,
    space: 6,
    desc: 'The study of the past, including events, societies, and individuals, with a focus on understanding how past events and actions continue to shape the present and future.',
    image: 'assets/webp/History.webp',
    cartquantity: 0,
  },
  {
    id: 5,
    subject: 'Geography',
    location: 'Block 1, Geography Lab',
    price: 375,
    space: 5,
    desc: 'The study of the earth and its features, including natural resources, climate, topography, and human populations and cultures.',
    image: 'assets/webp/geo.webp',
    cartquantity: 0,
  },
  {
    id: 6,
    subject: 'Physics',
    location: 'Block 9, Physics lab',
    price: 300,
    space: 7,
    desc: 'The study of matter, energy, and the fundamental laws of the universe, including mechanics, thermodynamics, and electromagnetism.',
    image: 'assets/webp/Physics.webp',
    cartquantity: 0,
  },
  {
    id: 7,
    subject: 'Chemistry',
    location: 'Block 4, Chemistry Lab',
    price: 250,
    space: 7,
    desc: 'The study of the properties, composition, and behavior of matter, including atoms, molecules, and chemical reactions.',
    image: 'assets/webp/Chemistry.webp',
    cartquantity: 0,
  },
  {
    id: 8,
    subject: 'Biology',
    location: 'Block 10, Biology Lab',
    price: 300,
    space: 6,
    desc: 'The study of living organisms, including their structure, function, and behavior, as well as their interactions with the environment.',
    image: 'assets/webp/Biology.webp',
    cartquantity: 0,
  },
  {
    id: 9,
    subject: 'Swimming',
    location: 'Block 7, Swimming Pool',
    price: 500,
    space: 9,
    desc: 'he physical and mental preparation required to swim at a competitive level, including strength and conditioning, stroke technique refinement, and race strategy development.',
    image: 'assets/webp/swim.webp',
    cartquantity: 0,
  },
  {
    id: 10,
    subject: 'Lego Robotics',
    location: 'Block 2, Robotics Lab',
    price: 175,
    space: 6,
    desc: 'A form of robotics engineering that involves building and programming robots using Lego building blocks and specialized software.',
    image: 'assets/webp/Lego.webp',
    cartquantity: 0,
  },
  {
    id: 11,
    subject: 'Cricket',
    location: 'Block 8, Class 207',
    price: 250,
    space: 9,
    desc: 'The physical and mental preparation required to play cricket at a competitive level, including skill development in batting, bowling, fielding, and strategy, as well as fitness and conditioning.',
    image: 'assets/webp/Cricket.webp',
    cartquantity: 0,
  },
  {
    id: 12,
    subject: 'Computer Science',
    location: 'Block 8, Computer Lab',
    price: 175,
    space: 4,
    desc: 'The study of computing and computational systems, including programming, algorithms, and data structures.',
    image: 'assets/webp/IT.webp',
    cartquantity: 0,
  },
  {
    id: 13,
    subject: 'Art',
    location: 'Block 5, Art Room',
    price: 250,
    space: 5,
    desc: 'The creation and appreciation of visual and/or performing arts, including painting, sculpture, music, theater, and dance.',
    image: 'assets/webp/Art.webp',
    cartquantity: 0,
  },
  {
    id: 14,
    subject: 'Music',
    location: 'Block 7, Music Room',
    price: 400,
    space: 6,
    desc: 'The creation and performance of sound and rhythm using instruments or the human voice, often with a focus on melody, harmony, and rhythm.',
    image: 'assets/webp/Music.webp',
    cartquantity: 0,
  },
  {
    id: 15,
    subject: 'Dance',
    location: 'Block 7, Dance Studio',
    price: 350,
    space: 4,
    desc: 'The expression of emotion or storytelling through movement, often with a focus on choreography, technique, and style.',
    image: 'assets/webp/dancing.webp',
    cartquantity: 0,
  },
];